server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          uri: http://gitlab-gitlab.apps.allinone.curiouser.com/Curiouser/ConfigCenter.git
          search-paths: '{application}'
          username: curiouser
          password: curiouser
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://user:password@localhost:8080/eureka/