spring:
  cloud:
    config:
      server:
        git:
          uri: http://github.com/RationalMonster/SpringCloudApplicationConfigCenter.git
          search-paths: '{application}'
          username: RationalMonster
          password: rM*51158.