spring:
  cloud:
    config:
      server:
        git:
          uri: http://gitlab-gitlab.apps.allinone.curiouser.com/Curiouser/ConfigCenter.git
          search-paths: '{application}'
          username: curiouser
          password: curiouser