spring:
  cloud:
    config:
      server:
        git:
          uri: http://gitlab-gitlab.apps.allinone.curiouser.com/Curiouser/ConfigCenter.git
          search-paths: '{application}'
          username: curiouser
          password: curiouser
eureka:
  instance:
    non-secure-port: 80
    ip-address: configserver-poseidon-ci.apps.test.openshift.com  
